[package]
name = "miso"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
keyring = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "5"
